### PR TITLE
Docs revamp

### PR DESCRIPTION
**Pull request by TransGirlCodes**
This PR updates the docs system to use the Documenter.jl's native html generator. 

I also split up the docs into a few different sections.

### CODE REVIEW

**Comment by TransGirlCodes** [comment]
@jangevaare Are you happy with this?

**Comment by jangevaare** [comment]
I think so! I was trying to figure out if I could view the rendered docs before merging - is the only way for me to build them from your branch locally?

**Comment by TransGirlCodes** [comment]
Yes I believe so, if there's another way to do it then I have not discovered it yet.

**Comment by jangevaare** [comment]
Okay, have done that now. Couple questions/comments:

- I think makelocal.jl can be removed now with this change.
- We were going to drop coveralls or codecov?
- Can index.md refer to README.md rather than duplicating its content?
- The alt text for the package badge is incorrect in README.md and index.md

**Comment by TransGirlCodes** [comment]
Sweet!:

I will address points 1 and 4. 

For point 2, I think we use codecov. We used to use two services for some reason in the beginning.

If we can reuse index.md that's a great idea. I don't know if documenter will do it, but we could give it a try!

**Comment by jangevaare** [comment]
Nice job, if there's nothing else you want to add I will merge.

**Comment by TransGirlCodes** [comment]
@jangevaare Turns out Documenter.jl does not work with relative paths in the make.jl so ../../README.md won't work, but a symbolic link will mean julia's IO just goes and opens it anyway!

**Comment by TransGirlCodes** [comment]
I think that's everything now :+1:

**Pull request merged**
