### PR TITLE
[WIP] Add genetic distance calculations under different substitution models

### PR DESCRIPTION
**Pull request by jangevaare**
- [x] Record differences between two sequences in a difference matrix
- [x] From difference matrix calculate proportions of substitutions, transitions, purine transitions, pyrimidine transitions, and transversions
- [ ] Add JC69 distance
- [ ] Add K80 distance
- [ ] Add F81 distance
- [ ] Add F84 distance
- [ ] Add HKY85 distance
- [ ] Add TN93 distance
- [ ] Add GTR distance

### CODE REVIEW

**Comment by jangevaare** [comment]
@Ward9250 I know you have started to implement some of these kinds of features in BioJulia/GeneticVariation.jl. Open to feedback to where certain features belong and the best way going about implementing them - especially the first two items I imagine!

**Comment by TransGirlCodes** [comment]
For recording the number of differences between sequences pairwise, you're right I've done quite a bit in both BioSequences.jl and GeneticVariation.jl. In BioSequences.jl I made a site-counting algorithm, which cycles through the compressed data of a BioSequence, and uses bit-parallel methods to compare many nucleotides in the same processor operations - up to 32 nucleotides for every 1 loop iteration. Different types of site could be counted - Match, Mismatch, Ambiguous and so on. Then, in GeneticVariation I define some methods which plug into that system, and add Mutated, Conserved, Transition, and Transversion (although I think transition and transversion need a bit more polishing first, but I'm sure I figured it out with a mate of mine at work). 

I've benchmarked it versus ape's C code, and iterating through each nucleotide of a sequence naively, and were surprised how much quicker it was.

**Comment by jangevaare** [comment]
That's great - I will switch over to those when they are ready and will extend as needed (more specificity than transition and transversion counts is required for some distance calculations). Unless you think all of this functionality belongs in GeneticVariation.jl, which I think would be quite reasonable too!

**Comment by TransGirlCodes** [comment]
So recently I've had a rethink about GeneticVariation as a result of a project where I had to create methods for counting: a) Gene frequencies in a sample, b) nucleotide diversity (according to Nei and Li 1979), and c). dN/dS according to the Nei and Gojobori 1986 method.

All of these originally went into GeneticVariation, but I decided to do a new package called NaturalSelection.jl to house the dN/dS method, and any other methods that infer selection.

The rationale being to prevent GeneticVariation becoming massive like Bio.jl did, GeneticVarition.jl keeps any methods to do with analysing genetic variation that are not really question or field specific - so computing allele frequencies, quantifying the level of diversity, they can stay as they are general and have all kinds of uses when working with variation. dNdS on the other hand, whilst it will require types and methods from GeneticVariation, will only typically be used by people interested in selection.

So for this I propose the following bikeshedding: GeneticVariation can define a genetic distance method, which will compute some basic distances that don't require models, such as hamming or p-distance (general - not field specific). Then SubstitutionModels can import and extend this method with a more evolution specific definition that accepts substitution model variables?

**Comment by jangevaare** [comment]
That seems reasonable to me!

**Pull request closed without merging**
