### PR TITLE
:art: changed substitution models to be mutable with setrate! function

### PR DESCRIPTION
**Pull request by coraallensavietta**
# Mutable NucleicAcidSubstitutionModels
## Types of changes
This PR implements the following changes:
* [x] :sparkles: New feature
* [ ] :bug: Bug fix (A non-breaking change, which fixes an issue).
* [ ] :boom: Breaking change (fix or feature that would cause existing functionality to change).

## :clipboard: Additional detail
Modifies all the NucleicAcidSubstitutionModels to allow them to be mutable with new function, setrate!.

We need the models to be mutable because we want to use this package in another package that will optimize model rates based on data.

```julia-repl
julia>  model = K80(0.5, 1.0);

julia> setrate!(model, [.5, .5])
Kimura 1980 model (absolute rate form)
α = 0.5, β = 0.5
```

## :ballot_box_with_check: Checklist

- [x] :art: The changes implemented is consistent with the [julia style guide](https://docs.julialang.org/en/stable/manual/style-guide/).
- [x] :blue_book: I have updated and added relevant docstrings, in a manner consistent with the [documentation styleguide](https://docs.julialang.org/en/stable/manual/documentation/).
- [x] :blue_book: I have added or updated relevant user and developer manuals/documentation in `docs/src/`.
- [x] :ok: There are unit tests that cover the code changes I have made.
- [x] :ok: The unit tests cover my code changes AND they pass.
- [ ] :pencil: I have added an entry to the `[UNRELEASED]` section of the manually curated `CHANGELOG.md` file for this repository.
I couldn't find this CHANGELOG.md file or a template, but I'd be happy to create one if you point me in the right direction.
- [x] :ok: All changes should be compatible with the latest stable version of Julia.
- [x] :thought_balloon: I have commented liberally for any complex pieces of internal code.

### CODE REVIEW

**Comment by coraallensavietta** [comment]
I'm not sure I understand how coverage is being calculated here -- there are lines that aren't colored either green or red, but which are run in tests. For example, [here](https://codecov.io/gh/BioJulia/SubstitutionModels.jl/pull/12/src/src/nucleic_acid/f81/relative.jl?before=src/nucleic_acid/f81/relative.jl)

It's also true that some cases aren't tested, like negative rates and rate vectors of incorrect length. I'd be happy to add these cases to our test file if that'd be helpful.

**Comment by jangevaare** [comment]
Hi!

Thanks for the PR.

It was a conscious design decision here to have substitution models immutable.

If we're allowing mutability it means we can do things like 
```
a = GTRrel(1.0, 2.0, 3.0, 4.0, 5.0, 0.1, 0.2, 0.3, 0.4)
a.α = -272
```

There's also a small performance hit to switch to mutable structs.

Can you explain a bit how your use case leads you to the mutability requirement - not possible, performant, and/or intuitive by some other means with immutable substitution models?

I can see how constructors using vectors would be useful - we should add that. I think there are some other things we can do with constructors and conversion methods to make these models and this package easier to work with - perhaps something that'd be useful to you..?

**Comment by cecileane** [comment]
I'll jump in, as Cora and I are working together. The motivation here is to reduce memory allocation and garbage collection when optimizing the rates of a substitution model from a sequence alignment, on a fixed phylogeny, and then on varying phylogenies as we optimize the phylogeny also. We will need to re-calculate the likelihood of an alignment with different rates, say hundreds or thousands of times (for hundreds or thousands of candidate values of rates). If we can re-use the memory allocated for the rates over and over, that would be saving memory allocation and saving garbage collection time.

I fully agree that any option to reduce memory allocation would suffer the risk that you mention: of a user modifying a rate with a non-permissible value. I don't see a way to have both (flexibility to re-assign rates, and safety against a user changing rates inappropriately). If you feel that safety is more important, then I can understand your point of view.

Actually, a better approach to reduce memory allocation might be to have the rates stored in a vector, but that would be a big change in your data structure, probably a breaking change. Perhaps something like this:

```julia
struct HKY85abs <: HKY85
  rate::Vector{Float64} # would be [α,β]
  π::Vector{Float64}    # would be [πA,πC,πG,πT]
  # checks for positivity etc.
end
```

Then we don't need a `mutable struct` because we could be re-assigning the values in the vector using, for example:

```julia
model = HKY85abs([1.0,2.0], [.2,.2,.3,.3])
model.rate[:] = [3.1, 4.1]
```

including the lack of safety:

```julia
model.π[1] = -2.0 
```

With the current data structure, I am not sure that we can indeed re-use previously allocated memory (with a `mutable struct` and scalars α and β). I don't know enough, really.

I have used this vector approach [here](https://github.com/crsl4/PhyloNetworks.jl/blob/master/src/substitutionModels.jl#L178) for models on a general state space, where I used the same approach as in `SubstitutionModels` to calculate the transition probabilities, in the hope to later use `SubstitutionModels` to deal with DNA.

[Here](https://github.com/crsl4/PhyloNetworks.jl/blob/master/src/traitsLikDiscrete.jl#L267) is where we modify the rates in place, to re-use already allocated memory, during optimization of rates. Does that help describe our use case?

**Comment by jangevaare** [comment]
Thanks! I will check this out.

I did something similar with my [old PhyloModels.jl package](https://github.com/jangevaare/PhyloModels.jl) in terms of the struct design for substitution models. I have to think back a bit here, but I believe the approach with SubstitutionModels.jl was at least partially because we wanted very friendly a.b type syntax for substitution model parameters.

In my work I've preferred to save a series of substitution models so that I can assess convergence after the fact, so that has influenced things here as well. I assumed that performance would be ok by just overwriting a substitution model when updating if that's what somebody wanted to do, but it sounds like that is worth benchmarking.

Side notes:
1. With Julia 0.7/1.0 (and I haven't looked into this much yet), I believe you can overload the the dot access syntax. So there might be a way to do both here - use vectors (ideally from StaticArrays package, which is already a dependency) for parameters and have the nice access syntax... There may be some ideas or functionality in Parameters.jl we may use here
2. It would also be nice to have unsafe constructors in terms of performance perhaps - considering that you can design your algorithms as to only generate appropriate values, or can just short circuit a likelihood calculation or something when unsupported values are introduced.

**Comment by cecileane** [comment]
> I assumed that performance would be ok by just overwriting a substitution model when updating if that's what somebody wanted to do, but it sounds like that is worth benchmarking.

What task would be worth benchmarking, do you think, and how to go about that? I don't have experience designing a good benchmark study. There's [BenchmarkTools](https://github.com/JuliaCI/BenchmarkTools.jl), but I never played with it.

**Comment by jangevaare** [comment]
Sorry for letting this get stale. I thought I responded to this one or not, guess not. Months later, is this still functionality you want?

In terms of benchmarks, I meant comparing repeated construction and overwriting of an immutable substitution model vs. having a mutable substitution model and using an update function repeatedly with it.

I do think an unsafe construction option is a good idea for highly optimized iterative algorithm use in general. A convenience feature for construction using vectors is also a good idea.

**Comment by cecileane** [comment]
No, we no longer need this functionality. You could close the PR. But thanks a lot for checking!

We went for an unsafe `setrates!` modifier for a more optimized iterative algorithm. We also chose to store the eigenvalue / eigenvector information for faster re-use & calculation of the transition probabilities. See [here](https://github.com/crsl4/PhyloNetworks.jl/blob/master/src/substitutionModels.jl#L34) for instance (with mention of the SubstitutionModels package) or [here](https://github.com/crsl4/PhyloNetworks.jl/blob/master/src/substitutionModels.jl#L779). I think that we also normalized the "relative" versions differently: to make sure that the average substitution rate is 1.0.

**Pull request closed without merging**
